# GitHub Actions workflow for deploying Python app to Azure Web App
name: Deploy Python app to Azure Web App - spamemaildetector

on:
  push:
    branches:
      - main   # Jab main branch pe push hoga tab run karega
  workflow_dispatch:   # Manual run option

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Azure Login
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DF53B94837514C42A0F6D285CD6D5EDA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B16F2E6433E24DE6A9431587620CDB1E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9BC076F096194DDF86211C87AC3FB05B }}

      # Step 5: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'spamemaildetector'   # Azure App ka exact name
          slot-name: 'Production'
          package: '.'
